version: '3.8'
services:
  deep-research-api:
    container_name: deep-research-api
    build: .
    env_file:
      - .env
    volumes:
      - ./:/app/
    ports:
      - "8001:8001"
    restart: unless-stopped
